demo_hybrid_pipeline:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: snowflake_account
      user: demo_user
      password: "demo_password"
      database: DEMO_DB
      warehouse: COMPUTE_WH
      schema: DEMO_SCHEMA
      threads: 1
      client_session_keep_alive: false
